name: Unit tests
on:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/yarn

      - name: Annotations and coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          annotations: failed-tests
          package-manager: yarn
          test-script: yarn test:ci
          github-token: ${{ secrets.GITHUB_TOKEN }}
